### ISSUE TITLE
Threshold size method?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick-plugins#1]
:information_source: See https://github.com/hsnr-gamera/gamera/issues/27

**Comment by ksharindam** [comment]
I will take a look at this

**Comment by ksharindam** [comment]
>  Maybe add size method?
> 
> ```
> Is <- thumbnail(I, WxH -> RxR) //small image
> Ib <- bicubic(Is, RxR -> WxH) //upscale small image
> Ith <- (sign(I - Ib + delta) < 0) ? 0 : 255 //threshold
> ```
> 
>  See also [jwilk/didjvu#15](https://github.com/jwilk/didjvu/issues/15)

What is that delta? a specifed number constant or an image?

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Delta - number, option, threshold regulator, default = 0. See https://github.com/hsnr-gamera/gamera/issues/27#issuecomment-641182532 (0 and 63). See also Bimod.

**Comment by ksharindam** [comment]
I used Qt smooth scaling instead of bicubic and got these results.
Threshold (delta) = 0
![lena0](https://user-images.githubusercontent.com/18181054/86263764-43ee1900-bbdf-11ea-8dac-9b00e446a316.png)

threshold = 10
![lena10](https://user-images.githubusercontent.com/18181054/86263782-4a7c9080-bbdf-11ea-89f8-0d420714182b.png)

threshold = 15
![lena15](https://user-images.githubusercontent.com/18181054/86263815-549e8f00-bbdf-11ea-959b-aa24f5b72323.png)

threshold = 20
![lena20](https://user-images.githubusercontent.com/18181054/86263855-5e27f700-bbdf-11ea-883d-ed8eb2c95ce8.png)

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Hmm. An interesting result. But you did not indicate the parameters (formula) of its receipt.

**Comment by ksharindam** [comment]
The formula used
(Ib - I) > threshold ? 0 : 255
which is mathematically same as what you have mentioned.
> Ith <- (sign(I - Ib + delta) < 0) ? 0 : 255

```cpp
    QImage scaledImg = img.scaledToWidth(imgW/32, Qt::SmoothTransformation);
    scaledImg = scaledImg.scaled(imgW, imgH, Qt::IgnoreAspectRatio, Qt::SmoothTransformation);

    for (int y=0; y<imgH; y++) {
        QRgb* line = (QRgb*) img.scanLine(y);
        QRgb* lineScaled = (QRgb*) scaledImg.constScanLine(y);
        for (int x=0; x<imgW; x++) {
            line[x] = ( qGray(lineScaled[x])) - qGray(line[x]) > thresh ? 0xff000000 : 0xffffffff;
        }
    }
```

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Not, R <- option (>= 1):
```cpp
QImage scaledImg = img.scaledToWidth(R, Qt::SmoothTransformation);
```
or
```cpp
QImage scaledImg = img.scaled(R, R, Qt::IgnoreAspectRatio, Qt::SmoothTransformation);
```

**Comment by ksharindam** [comment]
I think it is better to use R relative to image size(e.g imageWidth/32), rather than a fixed size or user defined variable.
But you can experiment with this for images of various sizes and see which gives better result.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

No, not better. With `R = ImageWidth / 32`, this method becomes the equivalent of Niblack (R = 16), and with `R = args` it becomes the equivalent of https://github.com/ImageProcessing-ElectronicPublications/aithreshold .

**Comment by ksharindam** [comment]
So what do you want?
And what will be the name of this filter?

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

I want the economical (memory) equivalent of "Adaptive Integral Thresholding". The name of this filter is "Threshold Size".

**Comment by ksharindam** [comment]
What parameters will it take?
1. downscaling size 
2. Threshold value
These two??

**Comment by ksharindam** [comment]
"Threshold Size" name is somewhat misleading.
You are thresholding according to the difference from blurred image.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Parameters (args):
1. downscaling size (default = 1, ~ bimod).
2. delta - value, regulator threshold (default = 0).

PS: Ok. "Threshold BG Scale"

**Comment by ksharindam** [comment]
"Threshold BG Scale" is a good name.
But default downscaling value 1 is not good. because when you upscale that 1pixel image all the pixels will be of same color as that 1 pixel. that means it becomes equivalent to simple threshold.

**Comment by ksharindam** [comment]
value of 8 is good enough

**Comment by zvezdochiot** [comment]
Ok, default = 8.
