### ISSUE TITLE
M_PI?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick-plugins#3]
https://github.com/ImageProcessing-ElectronicPublications/photoquick-plugins/blob/546a0485515337f78fcc17f00163b947c16d8f75/src/colors/kuwahara/kuwahara.cpp#L11-L12

Maybe?:
```cpp
#define MIN(a,b) (((a)<(b))?(a):(b))
#define MAX(a,b) (((a)>(b))?(a):(b))
#ifndef M_PI
#define M_PI 3.1415926535
#endif
```

**Comment by ksharindam** [comment]
M_PI is defined in cmath (or math.h). cmath is #included in kuwahara.cpp.
So there is no need to redefine it.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

I know. But on Win10 I ran into "undefined".

**Comment by ksharindam** [comment]
Which compiler are you using?

**Comment by zvezdochiot** [comment]
* http://kent.dl.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.8.2/threads-posix/dwarf/i686-4.8.2-release-posix-dwarf-rt_v3-rev3.7z
* http://download.qt.io/archive/qt/4.8/4.8.6/qt-opensource-windows-x86-mingw482-4.8.6-1.exe

**Comment by ksharindam** [comment]
I have compiled and packaged the photoquick , but never compiled the
plugins in windows before.
As you have told, i tested it today, and found that M_PI is not there.

Instead of defining M_PI, I prefer to replace M_PI as PI , which will be
defined as 7 digit float.

**Comment by zvezdochiot** [comment]
Hi  ksharindam .

Why not make a condition, as I suggested? Why superfluous entities? Not defined - define, defined - pass by.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

In my Win plugins work only when compiled with `libqtcored` and` libqtguid`. With `libqtcore` and` libqtgui` do not work.

**Comment by ksharindam** [comment]
I used M_PI.
But now found that avoiding double , and using float instead increases
noticable performance.
filters.cpp now uses float PI.
Otherwise i have no problem to use your suggestion.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Got it, `float`. Then:
```cpp
#ifndef M_PI
#define PI 3.1415926535f
#else
#define PI M_PI
#endif
```
Not?

**Comment by zvezdochiot** [comment]
Sorry:
#ifndef M_PI
#define PI 3.1415926535f
#else
#define PI (float)M_PI
#endif

**Comment by zvezdochiot** [comment]
Sorry:
```cpp
#ifndef M_PI
#define PI 3.1415926535f
#else
#define PI (float)M_PI
#endif
```
Not?

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Got it, `float`. Then:
```cpp
#ifndef M_PI
#define PI 3.1415926535f
#else
#define PI (float)M_PI
#endif
```
Not?

**Comment by ksharindam** [comment]
We dont need to get the value from M_PI and cast it to float. Because value
of pi is same everywhere.
So we can write simply in one line..
#define PI 3.141593f

(float contains maximum of 7 digits)

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

I agree. This is something I have fenced off too much.

**Comment by ksharindam** [comment]
> Hi @ksharindam .
> 
> In my Win plugins work only when compiled with `libqtcored` and` libqtguid`. With `libqtcore` and` libqtgui` do not work.

The reason may be using mingw64 instead of mingw32.
the prebuilt qt4 library is compiled against mingw32. so it may have compatibility issues with mingw64

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Not. I specifically compiled on x32.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Not. I specifically compiled on x32. Photoquick itself works, but does not load plugins.

**Comment by ksharindam** [comment]
What did you compile? the whole qt4 library?

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

I will explain:

Give: https://github.com/ImageProcessing-ElectronicPublications/photoquick-plugins/issues/3?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDExNjA5NjU4NTc6MTIzNzAwODI%3D#issuecomment-691519252

Option 1: Compile `photoquick` and` photoquick-plugins` with `libqtcored` and` libqtguid`. `Photoquick` starts, plugins are loaded.

Option 2: Compile `photoquick` and` photoquick-plugins` with `libqtcore` and` libqtgui`. `Photoquick` starts, plugins are not loaded.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

I will explain:

Give: https://github.com/ImageProcessing-ElectronicPublications/photoquick-plugins/issues/3#issuecomment-691519252

Option 1: Compile `photoquick` and `photoquick-plugins` with `libqtcored` and `libqtguid`. Photoquick starts, plugins are loaded.

Option 2: Compile `photoquick` and `photoquick-plugins` with `libqtcore` and `libqtgui`. Photoquick starts, plugins are not loaded.

**Comment by ksharindam** [comment]
Then may be there is some other reason

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Maybe I'm doing something wrong. I replace the libraries in the `Makefile` with" handles ".

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Maybe I'm doing something wrong. I replace libraries in `Makefile` with manual editing.

**Comment by ksharindam** [comment]
I tested the plugins.
It works when linked against QtGui4.dll and QtCore4.dll
But i did not test with debug libraries (QtGuid4.dll)

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

Hmm (no DEBUG mode):
```sh
g++ -s -mthreads -Wl,-subsystem,windows -o photoquick.exe object_script.photoquick  -L"c:\Qt\4.8.6\lib" -lmingw32 -lqtmaind -lgomp -lQtGuid4 -lQtCored4
```

`-lQtGuid4 -lQtCored4`! Maybe I don't understand something?

**Comment by ksharindam** [comment]
Why it is linking QtGuid4 in no debug mode?
It should link QtGui4 in no debug mode

**Comment by zvezdochiot** [comment]
>Hi @ksharindam .

So I was surprised. But when I edited the `Makefile` in both projects, the plugins stopped loading. Maybe I should try another build of Qt4?

PS: If use `strip` for `QtCored4.dll` and `QtGuid4.dll`, then everything works. If build with `QtCore4.dll` and` QtGui4.dll`, the plugins are not loaded. I don't nothing understand.

**Comment by zvezdochiot** [comment]
https://github.com/ImageProcessing-ElectronicPublications/photoquick-plugins/commit/a16cb33fe9fcb11187ae4e1edfd78a97119f91f9
