### ISSUE TITLE
uint -> int?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick-plugins#4]
Hi @ksharindam .

https://github.com/ImageProcessing-ElectronicPublications/photoquick-plugins/blob/66dfd3ddcee50e41c232a55b0670b38731e05c1f/src/transform/pixart-scaler/xbr.cpp#L57-L59

Maybe you should replace `uint` with `int` for cross-platform?

**Comment by ksharindam** [comment]
uint is cross platform (atleast in windows and linux). So it should not
create any problem.
So, until someone reports problem, i shall not replace uint with unsigned
int in other places.

But in this case, uint does not give extra advantage. And replacing with
int wont create any problem. So while doing other changes in the next
commit, i shall replace uint with int.

**Comment by zvezdochiot** [comment]
Ok.

Win10:
```sh
>qmake --version
QMake version 2.01a
Using Qt version 4.8.6 in C:\Qt\4.8.6\lib

>gcc --version
gcc (i686-posix-dwarf-rev3, Built by MinGW-W64 project) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

>g++ --version
g++ (i686-posix-dwarf-rev3, Built by MinGW-W64 project) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

>qmake .
>make
...
xbr.cpp:57:5: error: 'uint' was not declared in this scope
     uint y = (uint)(( 299*rg + 1000*g + 114*bg)/1000);
...
```

PS: src\colors\grayscale-local\color2gray.cpp line 14:
```cpp
#include <ctime>
```

**Comment by zvezdochiot** [comment]
Fixed https://github.com/ImageProcessing-ElectronicPublications/photoquick-plugins/commit/24200c47fa17ded56c1ea439840767c631f51581
