### ISSUE TITLE
Histogram?

### ISSUE THREAD

**Issue by zvezdochiot** [ImageProcessing-ElectronicPublications/photoquick-plugins#7]
Hi @ksharindam .

I really don't like your histograms:
* ![norm](https://i114.fastpic.ru/big/2021/0505/8c/128e7309e0366e602d436107379e9b8c.png)  
* ![log](https://i114.fastpic.ru/big/2021/0505/9f/64f211ec5a5f567eaea1e8693112369f.png)

For me, the ones that I get are much less bad:
* ![norm](https://i114.fastpic.ru/big/2021/0505/5d/485e306a0c55b5dbde8ba92f5088ee5d.png)  
* ![log](https://i114.fastpic.ru/big/2021/0505/85/d87e557b876fd8380506b83333232485.png)

See attachment:
[photoquick-plugins-hist.zip](https://github.com/ImageProcessing-ElectronicPublications/photoquick-plugins/files/6428039/photoquick-plugins-hist.zip)

PS: Accumulation mode can also be added:
```c
Hh = scale_h * k * hist[k];
```
But you will need a radiocheck and methods of working with it.

**Comment by ksharindam** [comment]
Actually I did not like the combination mode, in some cases it is less human readable.
But it is also useful, so you can add it.

**Comment by zvezdochiot** [comment]
Hi @ksharindam .

I don't want too much. The menu has already grown. I specially dropped the code for you so that you could experiment. The choice is always yours - you are the author. I don't want to crawl into someone else's.

**Comment by ksharindam** [comment]
For myself i have my own fork.
So feel free to do any change you want.

**Comment by zvezdochiot** [comment]
So we will simplify. "Quick" is so quick.
